package com.peknight.database.jdbc.aliyun.dms

import cats.effect.IO
import cats.effect.std.AtomicCell
import cats.effect.unsafe.implicits.global
import cats.syntax.option.*
import com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement.State

import java.sql.{Array as _, *}

/**
 * DMS JDBC Statement
 */
trait AliyunDmsStatement extends Statement:
  protected def connection: AliyunDmsConnection
  protected def stateCell: AtomicCell[IO, State]

  def executeQuery(sql: String): ResultSet = handleExecuteQuery(sql).unsafeRunSync()

  def executeUpdate(sql: String): Int = handleExecuteUpdate(sql).unsafeRunSync()

  def close(): Unit =
    stateCell.evalUpdate(state => state.currentResultSet
      .map(currentResultSet => currentResultSet.stateCell.update(s => s.copy(closed = true)))
      .getOrElse(IO.unit)
      .map(_ => state.copy(currentResultSet = None, closed = true))
    ).unsafeRunSync()

  def getMaxFieldSize: Int = 0

  def setMaxFieldSize(max: Int): Unit = ()

  def getMaxRows: Int = 400

  def setMaxRows(max: Int): Unit = ()

  def setEscapeProcessing(enable: Boolean): Unit = ()

  def getQueryTimeout: Int = 0

  def setQueryTimeout(seconds: Int): Unit = ()

  def cancel(): Unit = throw new SQLFeatureNotSupportedException("Cancel not supported")

  def getWarnings: SQLWarning = null

  def clearWarnings(): Unit = ()

  def setCursorName(name: String): Unit = throw new SQLFeatureNotSupportedException("Cursor not supported")

  def execute(sql: String): Boolean = handleExecute(sql).unsafeRunSync()

  def getResultSet: ResultSet = checkClosed(state => (state, state.currentResultSet)).orNull

  def getUpdateCount: Int = checkClosed(state => (state, state.updateCount.map(_.toInt))).getOrElse(-1)

  def getMoreResults: Boolean = false

  def setFetchDirection(direction: Int): Unit = ()

  def getFetchDirection: Int = ResultSet.FETCH_FORWARD

  def setFetchSize(rows: Int): Unit = ()

  def getFetchSize: Int = 0

  def getResultSetConcurrency: Int = ResultSet.CONCUR_READ_ONLY

  def getResultSetType: Int = ResultSet.TYPE_SCROLL_INSENSITIVE

  def addBatch(sql: String): Unit = notSupported

  def clearBatch(): Unit = notSupported

  def executeBatch(): Array[Int] = notSupported

  def getConnection: Connection = connection

  def getMoreResults(current: Int): Boolean = false

  def getGeneratedKeys: ResultSet =
    throw new SQLFeatureNotSupportedException("Generated keys not supported");

  def executeUpdate(sql: String, autoGeneratedKeys: Int): Int = executeUpdate(sql)

  def executeUpdate(sql: String, columnIndexes: Array[Int]): Int = executeUpdate(sql)

  def executeUpdate(sql: String, columnNames: Array[String]): Int = executeUpdate(sql)

  def execute(sql: String, autoGeneratedKeys: Int): Boolean = execute(sql)

  def execute(sql: String, columnIndexes: Array[Int]): Boolean = execute(sql)

  def execute(sql: String, columnNames: Array[String]): Boolean = execute(sql)

  def getResultSetHoldability: Int = ResultSet.HOLD_CURSORS_OVER_COMMIT

  def isClosed: Boolean = stateCell.get.map(_.closed).unsafeRunSync()

  def setPoolable(poolable: Boolean): Unit = ()

  def isPoolable: Boolean = false

  def closeOnCompletion(): Unit = ()

  def isCloseOnCompletion: Boolean = false

  def unwrap[T](iface: Class[T]): T = handleUnwrap(iface)

  def isWrapperFor(iface: Class[?]): Boolean = iface.isInstance(this)

  protected def handleExecuteQuery(sql: String): IO[ResultSet] =
    closeCurrentResultSet { state =>
      for
        result <- connection.client.executeScript[IO](connection.databaseId, sql)
        currentResultSet <- AliyunDmsResultSet(this.some, result.columnNames, result.rows)
      yield
        (state.copy(currentResultSet = currentResultSet.some, updateCount = None), currentResultSet)
    }

  protected def handleExecuteUpdate(sql: String): IO[Int] =
    closeCurrentResultSet(state => connection.client.executeScript[IO](connection.databaseId, sql).map(result =>
      (state.copy(updateCount = result.rowCount.some), result.rowCount.toInt)
    ))

  protected def handleExecute(sql: String): IO[Boolean] =
    closeCurrentResultSet(state => connection.client.executeScript[IO](connection.databaseId, sql).flatMap(result =>
      if result.columnNames.nonEmpty then
        AliyunDmsResultSet(this.some, result.columnNames, result.rows)
          .map(currentResultSet => (state.copy(currentResultSet = currentResultSet.some, updateCount = None), true))
      else IO((state.copy(updateCount = result.rowCount.some), false))
    ))

  private def checkClosed[T](f: State => (State, T)): T =
    stateCell.evalModify[T](state =>
      if state.closed then IO.raiseError(new SQLException("Statement is closed")) else IO(f(state))
    ).unsafeRunSync()

  private def closeCurrentResultSet[T](f: State => IO[(State, T)]): IO[T] =
    stateCell.evalModify[T](state =>
      if state.closed then IO.raiseError(new SQLException("Statement is closed"))
      else
        state.currentResultSet match
          case Some(currentResultSet) => currentResultSet.stateCell.update(s => s.copy(closed = true))
            .flatMap(_ => f(state.copy(currentResultSet = None)))
          case _ => f(state)
    )

  protected def notSupportBatch[T]: T =
    throw new SQLFeatureNotSupportedException("Batch not supported")

end AliyunDmsStatement
object AliyunDmsStatement:
  private[dms] case class State(currentResultSet: Option[AliyunDmsResultSet] = None,
                                updateCount: Option[Long] = None,
                                closed: Boolean = false)
  case class AliyunDmsStatement(connection: AliyunDmsConnection, stateCell: AtomicCell[IO, State])
    extends com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement
  def apply(connection: AliyunDmsConnection): IO[com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement] =
    AtomicCell[IO]
      .of(State())
      .map(stateCell => AliyunDmsStatement(connection, stateCell))
end AliyunDmsStatement
