package com.peknight.database.jdbc.aliyun.dms

import cats.effect.IO
import cats.effect.std.AtomicCell
import cats.effect.unsafe.implicits.global

import java.sql.{Array as _, *}
import java.util.Properties
import java.util.concurrent.Executor
import java.{sql, util}

/**
 * DMS JDBC Connection
 *
 * 不支持事务，每次调用 ExecuteScript 都是独立的 HTTP 请求
 */
case class AliyunDmsConnection(client: AliyunDmsClient, databaseId: Int, closedCell: AtomicCell[IO, Boolean])
  extends Connection:
  def createStatement(): Statement = checkClosed(AliyunDmsStatement(this))

  def prepareStatement(sql: String): PreparedStatement = checkClosed(AliyunDmsPreparedStatement(this, sql))

  def prepareCall(sql: String): CallableStatement = throw new SQLFeatureNotSupportedException("prepareCell not supported")

  def nativeSQL(sql: String): String = sql

  def setAutoCommit(autoCommit: Boolean): Unit =
    if autoCommit then notSupportTransactions else ()

  def getAutoCommit = true

  def commit(): Unit = notSupportTransactions

  def rollback(): Unit = notSupportTransactions

  def close(): Unit = closedCell.set(true).unsafeRunSync()

  def isClosed: Boolean = closedCell.get.unsafeRunSync()

  def getMetaData: DatabaseMetaData = checkClosed(IO(AliyunDmsDatabaseMetaData(this)))

  def setReadOnly(readOnly: Boolean): Unit = ()

  def isReadOnly = true

  def setCatalog(catalog: String): Unit = ()

  def getCatalog: String = null

  def setTransactionIsolation(level: Int): Unit = notSupportTransactions

  def getTransactionIsolation: Int = Connection.TRANSACTION_NONE

  def getWarnings: SQLWarning = null

  def clearWarnings(): Unit = ()

  def createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement = createStatement()

  def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement =
    prepareStatement(sql)

  def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement = prepareCall(sql)

  def getTypeMap: util.Map[String, Class[?]] = notSupported

  def setTypeMap(map: util.Map[String, Class[?]]): Unit = notSupported

  def setHoldability(holdability: Int): Unit = ()

  def getHoldability: Int = ResultSet.HOLD_CURSORS_OVER_COMMIT

  def setSavepoint(): Savepoint = throw new SQLFeatureNotSupportedException("DMS does not support savepoints")

  def setSavepoint(name: String): Savepoint = setSavepoint()

  def rollback(savepoint: Savepoint): Unit = notSupportTransactions

  def releaseSavepoint(savepoint: Savepoint): Unit = throw new SQLFeatureNotSupportedException("DMS does not support savepoints")

  def createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement = createStatement()

  def prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement =
    prepareStatement(sql)

  def prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement =
    prepareCall(sql)

  def prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = prepareStatement(sql)

  def prepareStatement(sql: String, columnIndexes: Array[Int]): PreparedStatement = prepareStatement(sql)

  def prepareStatement(sql: String, columnNames: Array[String]): PreparedStatement = prepareStatement(sql)

  def createClob(): Clob = notSupported

  def createBlob(): Blob = notSupported

  def createNClob(): NClob = notSupported

  def createSQLXML(): SQLXML = notSupported

  def isValid(timeout: Int): Boolean = !closedCell.get.unsafeRunSync()

  def setClientInfo(name: String, value: String): Unit = ()

  def setClientInfo(properties: Properties): Unit = ()

  def getClientInfo(name: String): String = null

  def getClientInfo = new Properties()

  def createArrayOf(typeName: String, elements: Array[AnyRef]): sql.Array = notSupported

  def createStruct(typeName: String, attributes: Array[AnyRef]): Struct = notSupported

  def setSchema(schema: String): Unit = ()

  def getSchema: String = null

  def abort(executor: Executor): Unit = close()

  def setNetworkTimeout(executor: Executor, milliseconds: Int): Unit = ()

  def getNetworkTimeout = 0

  def unwrap[T](iface: Class[T]): T = handleUnwrap(iface)

  def isWrapperFor(iface: Class[?]): Boolean = iface.isInstance(this)

  private def checkClosed[T](t: IO[T]) =
    closedCell.get
      .flatMap(closed => if closed then IO.raiseError(new SQLException("Connection is closed")) else t)
      .unsafeRunSync()

  private def notSupportTransactions[T]: T =
    throw new SQLFeatureNotSupportedException("DMS does not support transactions")
end AliyunDmsConnection
object AliyunDmsConnection:
  def apply(client: AliyunDmsClient, databaseId: Int): IO[AliyunDmsConnection] =
    AtomicCell[IO]
      .of[Boolean](false)
      .map(closedCell => AliyunDmsConnection(client, databaseId, closedCell))
end AliyunDmsConnection
