package com.peknight.database.jdbc.aliyun.dms

import cats.effect.IO
import cats.effect.std.AtomicCell
import com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement.State

import java.sql.{Connection, ResultSet, SQLWarning, Statement}

/**
 * DMS JDBC Statement
 */
trait AliyunDmsStatement extends Statement:
  protected def connection: AliyunDmsConnection
  protected def stateCell: AtomicCell[IO, State]

  def executeQuery(sql: String): ResultSet = ???

  def executeUpdate(sql: String): Int = ???

  def close(): Unit = ???

  def getMaxFieldSize: Int = ???

  def setMaxFieldSize(max: Int): Unit = ???

  def getMaxRows: Int = ???

  def setMaxRows(max: Int): Unit = ???

  def setEscapeProcessing(enable: Boolean): Unit = ???

  def getQueryTimeout: Int = ???

  def setQueryTimeout(seconds: Int): Unit = ???

  def cancel(): Unit = ???

  def getWarnings: SQLWarning = ???

  def clearWarnings(): Unit = ???

  def setCursorName(name: String): Unit = ???

  def execute(sql: String): Boolean = ???

  def getResultSet: ResultSet = ???

  def getUpdateCount: Int = ???

  def getMoreResults: Boolean = ???

  def setFetchDirection(direction: Int): Unit = ???

  def getFetchDirection: Int = ???

  def setFetchSize(rows: Int): Unit = ???

  def getFetchSize: Int = ???

  def getResultSetConcurrency: Int = ???

  def getResultSetType: Int = ???

  def addBatch(sql: String): Unit = ???

  def clearBatch(): Unit = ???

  def executeBatch(): Array[Int] = ???

  def getConnection: Connection = ???

  def getMoreResults(current: Int): Boolean = ???

  def getGeneratedKeys: ResultSet = ???

  def executeUpdate(sql: String, autoGeneratedKeys: Int): Int = ???

  def executeUpdate(sql: String, columnIndexes: Array[Int]): Int = ???

  def executeUpdate(sql: String, columnNames: Array[String]): Int = ???

  def execute(sql: String, autoGeneratedKeys: Int): Boolean = ???

  def execute(sql: String, columnIndexes: Array[Int]): Boolean = ???

  def execute(sql: String, columnNames: Array[String]): Boolean = ???

  def getResultSetHoldability: Int = ???

  def isClosed: Boolean = ???

  def setPoolable(poolable: Boolean): Unit = ???

  def isPoolable: Boolean = ???

  def closeOnCompletion(): Unit = ???

  def isCloseOnCompletion: Boolean = ???

  def unwrap[T](iface: Class[T]): T = ???

  def isWrapperFor(iface: Class[?]): Boolean = ???
end AliyunDmsStatement
object AliyunDmsStatement:
  private[dms] case class State(currentResultSet: Option[AliyunDmsResultSet] = None,
                                updateCount: Option[Long] = None,
                                closed: Boolean = false)
  case class AliyunDmsStatement(connection: AliyunDmsConnection, stateCell: AtomicCell[IO, State])
    extends com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement
  def apply(connection: AliyunDmsConnection): IO[com.peknight.database.jdbc.aliyun.dms.AliyunDmsStatement] =
    AtomicCell[IO]
      .of(State())
      .map(stateCell => AliyunDmsStatement(connection, stateCell))
end AliyunDmsStatement
